name: Build to GitHub Pages
on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.x
            - run: curl https://raw.githubusercontent.com/spacebarchat/spacebarchat/master/CODE_OF_CONDUCT.md -o docs/contributing/conduct.md
            - run: python3 -m pip install -r requirements.txt
            - run: mkdocs build
            - run: echo docs.spacebar.chat >> site/CNAME
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.3
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: site # The folder the action should deploy.
